#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config initial_polarity     second_child
bspc config automatic_scheme	 longest_side

bspc config single_monocle	 false
bspc config borderless_monocle   true
bspc config gapless_monocle      true

for i in top right bottom left; do
	bspc config "${i}"_monocle_padding 0
done
unset i

bspc config focus_follows_pointer true

bspc config normal_border_color "#800000"
bspc config active_border_color "#ff0000"
bspc config focused_border_color "#ff0000"
bspc config presel_border_color "#2a2829"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
